#!/usr/bin/env python3
"""检查全部提交的作者身份，拦住 Cursor 等额外贡献者。

只看 git 元数据（author、committer、说明与 trailer），不扫描工作区文件。
禁令文档里可以出现这些词；提交记录里不可以。

用法：python check_commit_identity.py
退出码：0 = 通过；1 = 发现非预期身份或署名。
"""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
AUTHOR = "chengzhao-dev"
FORBIDDEN = (
    "co-authored-by",
    "signed-off-by",
    "cursoragent",
    "made with cursor",
    "generated by cursor",
    "cursor",
)


def git_log():
    result = subprocess.run(
        ["git", "log", "--all", "--format=%H%x1f%an%x1f%cn%x1f%B%x1e"],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    text = result.stdout.decode("utf-8", errors="replace")
    if result.returncode != 0:
        return None, text
    return text, ""


def main() -> int:
    text, error = git_log()
    if text is None:
        print(f"提交身份检查失败：无法读取 git 历史\n{error}")
        return 1
    problems = []
    for record in text.split("\x1e"):
        record = record.strip()
        if not record:
            continue
        parts = record.split("\x1f", 3)
        if len(parts) < 4:
            continue
        sha, author, committer, body = parts
        if author != AUTHOR or committer != AUTHOR:
            problems.append(f"{sha[:10]} 作者 {author} / 提交者 {committer}")
            continue
        folded = body.casefold()
        for word in FORBIDDEN:
            if word in folded:
                problems.append(f"{sha[:10]} 说明含「{word}」")
                break
    if problems:
        print(f"提交身份检查失败（{len(problems)} 项）：")
        for item in problems[:30]:
            print(f"  {item}")
        return 1
    print("提交身份检查通过：全部提交都是 chengzhao-dev，且没有额外署名")
    return 0


if __name__ == "__main__":
    sys.exit(main())
